[build]
  command = "npm run build"
  publish = ".next/standalone"

[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
